name: CI 
on:
  push:
    branches:
      - main
    paths:
      - "./src/**"
      - "./pom.xml"
      - "./Dockerfile"
  workflow_dispatch:

permissions:
  contents: write
jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "."
          file: "./Dockerfile"
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/fullstack-blogging-app:${{ github.run_number }}

      
  change-image-in-helm-chart-and-k8s-manifest:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yq
        uses: dcarbone/install-yq-action@v1.1.1
        with:
          version: 'v4.40.5'

      - name: Update image tag in Helm chart and K8s manifest
        run: |
          IMAGE_TAG="${{ github.run_number }}"
          REPO_NAME="${{ vars.DOCKERHUB_USERNAME }}/fullstack-blogging-app"

          # 1. Update Helm Chart
          yq -i ".app.image.repository = \"$REPO_NAME\"" ./Helm/values.yaml
          yq -i ".app.image.tag = \"$IMAGE_TAG\"" ./Helm/values.yaml

          # sed -i "/^app:/,/^[^ ]/ s|repository: .*|repository: $REPO_NAME|" ./Helm/values.yaml
          # sed -i "/^app:/,/^[^ ]/ s|tag: .*|tag: \"$IMAGE_TAG\"|" ./Helm/values.yaml
          
          # 2. Update K8s manifest

          yq -i ".spec.template.spec.containers[0].image = \"$REPO_NAME:$IMAGE_TAG\"" ./k8s/application.yaml

          # sed -i "s|image: $REPO_NAME:.*|image: $REPO_NAME:$IMAGE_TAG|" ./k8s/application.yaml

          # 3. Commit and push changes
          
          git config --global user.name "CI"
          git config --global user.email "ci@action.github.com"
          git add ./Helm/values.yaml ./k8s/application.yaml
          git commit -m "Update image to $REPO_NAME:$IMAGE_TAG"
          git push origin main

